import pytest

from src.scanner.scanner import Scanner


@pytest.fixture(scope="class")
def _scanner(request: pytest.FixtureRequest) -> None:
    """Fixture function to share results from scan to class."""
    filename = "test1.cmm"
    cmm_scanner = Scanner(filename)
    request.cls.results = cmm_scanner.scan()


@pytest.mark.usefixtures("_scanner")
class TestExample1:
    """Class to bundle tests for 'test1.cmm' file."""

    def test_output(cls) -> None:
        """Test for scanner output."""
        output = cls.results[0]
        expected_output = [
            (38, 1),
            1,
            (34, 1),
            26,
            (35, 1),
            27,
            20,
            3,
            (34, 2),
            20,
            2,
            (34, 3),
            20,
            2,
            (34, 4),
            26,
            (35, 1),
            27,
            20,
            1,
            (34, 5),
            24,
            2,
            (34, 6),
            26,
            27,
            21,
            1,
            (34, 7),
            21,
            1,
            (34, 8),
            25,
            28,
            1,
            (34, 9),
            20,
            2,
            (34, 10),
            20,
            1,
            (34, 11),
            20,
            (34, 11),
            18,
            (34, 7),
            20,
            (34, 10),
            18,
            (34, 6),
            26,
            (34, 7),
            27,
            20,
            (34, 9),
            18,
            (34, 7),
            12,
            (35, 2),
            20,
            8,
            24,
            (34, 9),
            16,
            (34, 8),
            25,
            28,
            5,
            24,
            (34, 6),
            26,
            (34, 9),
            27,
            16,
            (34, 1),
            25,
            28,
            (34, 10),
            18,
            (34, 6),
            26,
            (34, 9),
            27,
            20,
            (34, 11),
            18,
            (34, 9),
            20,
            29,
            (34, 9),
            18,
            (34, 9),
            12,
            (35, 2),
            20,
            29,
            11,
            (34, 11),
            20,
            29,
            (38, 2),
            4,
            (34, 12),
            24,
            2,
            (34, 6),
            26,
            27,
            21,
            1,
            (34, 7),
            21,
            1,
            (34, 8),
            25,
            28,
            1,
            (34, 9),
            20,
            1,
            (34, 11),
            20,
            (34, 9),
            18,
            (34, 7),
            20,
            8,
            24,
            (34, 9),
            16,
            (34, 8),
            13,
            (35, 2),
            25,
            28,
            2,
            (34, 13),
            20,
            (34, 11),
            18,
            (34, 5),
            24,
            (34, 6),
            21,
            (34, 9),
            21,
            (34, 8),
            25,
            20,
            (34, 13),
            18,
            (34, 6),
            26,
            (34, 11),
            27,
            20,
            (34, 6),
            26,
            (34, 11),
            27,
            18,
            (34, 6),
            26,
            (34, 9),
            27,
            20,
            (34, 6),
            26,
            (34, 9),
            27,
            18,
            (34, 13),
            20,
            (34, 9),
            18,
            (34, 9),
            12,
            (35, 2),
            20,
            29,
            11,
            20,
            29,
            (38, 3),
            4,
            (34, 14),
            24,
            4,
            25,
            28,
            1,
            (34, 9),
            20,
            (34, 2),
            18,
            (37, 1),
            20,
            10,
            24,
            (34, 2),
            25,
            20,
            9,
            24,
            (34, 3),
            25,
            20,
            8,
            24,
            (34, 9),
            16,
            (35, 1),
            25,
            28,
            (34, 2),
            18,
            (37, 2),
            20,
            10,
            24,
            (34, 2),
            25,
            20,
            9,
            (34, 1),
            26,
            (34, 9),
            27,
            20,
            (34, 4),
            26,
            (34, 9),
            27,
            18,
            (34, 1),
            26,
            (34, 9),
            27,
            14,
            (34, 3),
            20,
            (34, 9),
            18,
            (34, 9),
            12,
            (35, 2),
            20,
            29,
            11,
            20,
            29,
            (38, 4),
            4,
            (34, 15),
            24,
            4,
            25,
            28,
            1,
            (34, 9),
            20,
            (34, 9),
            18,
            (35, 3),
            20,
            8,
            24,
            (34, 9),
            16,
            (35, 1),
            25,
            28,
            10,
            (34, 4),
            26,
            (34, 9),
            27,
            20,
            (34, 9),
            18,
            (34, 9),
            12,
            (35, 2),
            20,
            29,
            11,
            20,
            29,
            (38, 5),
            4,
            (34, 16),
            24,
            4,
            25,
            28,
            (34, 2),
            18,
            (37, 3),
            20,
            10,
            24,
            (34, 2),
            25,
            20,
            (34, 14),
            24,
            25,
            20,
            (34, 2),
            18,
            (37, 4),
            20,
            10,
            24,
            (34, 2),
            25,
            20,
            (34, 12),
            24,
            (34, 4),
            21,
            (35, 3),
            21,
            (35, 1),
            25,
            20,
            (34, 2),
            18,
            (37, 5),
            20,
            10,
            24,
            (34, 2),
            25,
            20,
            (34, 15),
            24,
            25,
            20,
            11,
            20,
            29,
            (38, 6),
        ]
        assert output == expected_output

    def test_id_table(cls) -> None:
        """Test for scanner identifier symbol table."""
        id_symbol_table = cls.results[1]
        expected_id_symbol_table = {
            1: "x",
            2: "s",
            3: "f1",
            4: "f2",
            5: "miniloc",
            6: "a",
            7: "low",
            8: "high",
            9: "i",
            10: "y",
            11: "k",
            12: "sort",
            13: "t",
            14: "readArray",
            15: "writeArray",
            16: "main",
        }
        assert id_symbol_table == expected_id_symbol_table

    def test_int_table(cls) -> None:
        """Test for scanner integer symbol table."""
        int_symbol_table = cls.results[2]
        expected_int_symbol_table = {1: 10, 2: 1, 3: 0}
        assert int_symbol_table == expected_int_symbol_table

    def test_float_table(cls) -> None:
        """Test for scanner float symbol table."""
        float_symbol_table = cls.results[3]
        expected_float_symbol_table = {}
        assert float_symbol_table == expected_float_symbol_table

    def test_str_table(cls) -> None:
        """Test for scanner string symbol table."""
        str_symbol_table = cls.results[4]
        expected_str_symbol_table = {
            1: '"Enter a float number: "',
            2: '"Enter an integer number: "',
            3: '"Reading Information….."',
            4: '"Sorting….."',
            5: '"Sorted Array:"',
        }
        assert str_symbol_table == expected_str_symbol_table

    def test_comment_table(cls) -> None:
        """Test for scanner comment symbol table."""
        comment_symbol_table = cls.results[5]
        expected_comment_symbol_table = {
            1: "/* Program that reads a 10 element array of\nintegers, and then multiply each element of\nthe array by a float, stores the result into an\narray of floats. Subsequently, the array of\nfloats is sorted and display it into standard\noutput.*/",
            2: "/* END of miniloc() */",
            3: "/* END of sort() */",
            4: "/* END of readArray() */",
            5: "/* END of writeArray() */",
            6: "/* END of main() */",
        }
        assert comment_symbol_table == expected_comment_symbol_table
